version: "3.3"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - "./:/usr/app"
  db:
    image: mongo
    container_name: "database"
    restart: always
    volumes:
      - dbdata:/data/db
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  dbdata: