POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

###
DELETE http://localhost:8080/books/sx94wmgbvcd9n2u
Accept: application/json

###
POST http://localhost:8080/books/edit/o6ozgjjnxcr3xxp
Content-Type: application/json

{
  "ISBN": "o6ozgjjnxcr3xxp",
  "price": "1231",
  "title": "asd"
}

###




