DELETE http://localhost:8080/books/4ansef7nceibot7
Accept: application/json

###
POST http://localhost:8080/books/create
Content-Type: application/json

{
  "title": "Book3",
  "author": "Author3",
  "ISBN": "ISBN",
  "price": "1231"
}

###


